export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  TRANSFER = 'TRANSFER',
  REVERSAL_WITHDRAWAL = 'REVERSAL_WITHDRAWAL',
  REVERSAL_DEPOSIT = 'REVERSAL_DEPOSIT',
  REVERSAL_TRANSFER = 'REVERSAL_TRANSFER',
}